version: "0.1"

x-common-mysql-env: &common-mysql-env
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: my-user
  MYSQL_PASSWORD: my-user-pwd

services:
  mysql:
    container_name: mysql-local
    image: mysql:latest
    environment:
      MYSQL_DATABASE: myapp_db
      <<: *common-mysql-env
    volumes:
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    command: --authentication_policy=mysql_native_password
